#!/bin/bash

function colorscheme
{
        sed -i 's/include.*/include <\/home\/raj\/.config\/colorschemes\/blossom_light>/' ~/.config/X11/xresources
        xrdb $HOME ~/.config/X11/xresources
}

function wall
{
        feh --bg-fill ~/Pictures/blossom.*
}

function rundunst
{
        killall dunst
        run_dunst &
}
function shadows

{
    killall picom
    picom --config ~/.config/picom/picom.conf &
}

function bspwmrc
{
    sed -i 's/config normal_border_color.*/config normal_border_color     "#f5f5f9"/' ~/.config/bspwm/bspwmrc
    sed -i 's/config focused_border_color.*/config focused_border_color     "$color5"/' ~/.config/bspwm/bspwmrc
    bspc wm -r
}

colorscheme
wall
rundunst
shadows
bspwmrc
