#!/bin/bash

function colorscheme
{
    sed -i 's/include.*/include <\/home\/raj\/.config\/colorschemes\/blossom>/' ~/.config/X11/xresources
    xrdb $HOME ~/.config/X11/xresources
}

function wall
{
    feh --bg-fill ~/Pictures/blossom.*
}

function rundunst
{
    killall dunst
    run_dunst &
}

function bspwmrc
{
    sed -i 's/config normal_border_color.*/config normal_border_color   "$bg"/' ~/.config/bspwm/bspwmrc
    sed -i 's/config focused_border_color.*/config focused_border_color     "$fg"/' ~/.config/bspwm/bspwmrc
    bspc wm -r
}

colorscheme
wall
killall picom
rundunst
shadows
bspwmrc
