#!/bin/bash

function colorscheme
{
    sed -i 's/include.*/include <\/home\/raj\/.config\/colorschemes\/blossom>/' ~/.config/X11/xresources
    xrdb $HOME ~/.config/X11/xresources
}

function wall
{
    feh --bg-fill ~/Pictures/blossom3.*
}

function rundunst
{
    killall dunst
    run_dunst &
}

function compositor
{
    killall picom
    picom --config ~/.config/picom/picom.conf &
}

function bspwmrc
{
    sed -i 's/config normal_border_color.*/config normal_border_color   "$bg"/' ~/.config/bspwm/bspwmrc
    sed -i 's/config focused_border_color.*/config focused_border_color     "$fg"/' ~/.config/bspwm/bspwmrc
    bspc wm -r
}

colorscheme
wall
compositor
rundunst
shadows
bspwmrc
