#!/bin/bash

function colorscheme
{
        sed -i 's/include.*/include <\/home\/raj\/.config\/colorschemes\/faint_light>/' ~/.config/X11/xresources
        xrdb $HOME ~/.config/X11/xresources
}

function wall
{
        feh --bg-fill ~/Pictures/faint_light.*
}

function rundunst
{
        killall dunst
        run_dunst &
}

function shadows
{
    killall picom
    picom --config ~/.config/picom/picom_shadows.conf &
}

function bspwmrc
{
    sed -i 's/config normal_border_color.*/config normal_border_color     "$bg"/' ~/.config/bspwm/bspwmrc
    sed -i 's/config focused_border_color.*/config focused_border_color     "#74838c"/' ~/.config/bspwm/bspwmrc
    bspc wm -r
}

colorscheme
wall
rundunst
shadows
bspwmrc
