#!/bin/bash

#change colorscheme in xresources
sed -i 's/include.*/include <\/home\/raj\/.config\/colorschemes\/faint_light>/' ~/.config/X11/xresources

#reload xresources
xrdb $HOME ~/.config/X11/xresources

#change wall using feh
feh --bg-fill ~/Pictures/faint_light.jpg

#colors
export background=$(xrdb ~/.config/X11/xresources -query all | grep background | awk '{print $2}')
export foreground=$(xrdb ~/.config/X11/xresources -query all | grep foreground | awk '{print $2}')

#change dunst colors
killall dunst
sed -i "s|background.*|background = \"$background\"|g" ~/.config/dunst/dunstrc
sed -i "s|foreground.*|foreground = \"$foreground\"|g" ~/.config/dunst/dunstrc

#dunst corners
sed -i "s|corner_radius.*|corner_radius = 0|g" ~/.config/dunst/dunstrc

#add border
sed -i "s|bspc config border_width.*|bspc config border_width 2 |g" ~/.config/bspwm/bspwmrc
sed -i "s|bspc config normal_border_color.*|bspc config normal_border_color  \"$background\"|g" ~/.config/bspwm/bspwmrc
sed -i "s|bspc config focused_border_color.*|bspc config focused_border_color   \"#949EA4\"|g" ~/.config/bspwm/bspwmrc

#compositor
killall picom
picom --config ~/.config/picom/picom_shadow.conf &

#restart bspwm
bspc wm -r
