#!/bin/bash

function portage_sync
{
        echo -n "Portage sync? ([y]/n)"
        read key -n1 -e -r 2> /dev/null
        if [ "$key" == "y" ]; then
                echo "Syncing Portage"
                sudo emerge --sync
        else
                echo
        fi
}

function new_use
{
        echo -n "New use? ([y]/n)"
        read key -n1 -e -r 2> /dev/null
        if [ "$key" == "y" ]; then
                sudo emerge --update --newuse --deep --quiet @world
        else
                echo
        fi
}

function update_system
{
        echo -n "Start system update? ([y]/n)"
        read key -n1 -e -r 2> /dev/null
        if [ "$key" == "y" ]; then
                sudo emerge -uDU --keep-going --with-bdeps=y @world
        else
                echo
        fi
}

function depclean
{
        sudo emerge --depclean
}

portage_sync
new_use
update_system
depclean
notify-send "System Updated"
