#!/bin/sh

focused=$(xrdb ~/.config/X11/xresources -query all | grep color7: | cut -f2)
normal=$(xrdb ~/.config/X11/xresources -query all | grep color0: | cut -f2)

bspc monitor -d term web code files media extra

bspc config focused_border_color	"$focused"
bspc config normal_border_color		"$normal"
bspc config border_width		    3
bspc config window_gap 			    8
bspc config focus_follows_pointer	false
bspc config top_padding             30
bspc config split_ratio			    0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		    false
bspc config single_monocle		    true

bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a mpv desktop='^5' state=fullscreen follow=on
bspc rule -a feh state=floating follow=on

run_dunst &
$HOME/.config/polybar/launch.sh &
